title: Koushik Kumar Ganeeb
subtitle: Koushik Kumar Ganeeb
description: >- # this means to ignore newlines until "baseurl:"
  My name is Koushik Kumar Ganeeb, working as a Principal Software Engineer at Salesforce with over 14+ years of experience as a Data Architect and Engineering Leader in various sectors of Software Development, I believe I bring a unique perspective and a wealth of knowledge to contribute to the membership community.

url: "https://master--melodious-hamster-a1de67.netlify.app" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blogs
      url: /blog
    - text: Contact
      url : /contact
    - text: Committees
      url : /committee


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: koushik.png
author: Koushik Kumar Ganeeb
author_bio: Welcome! My name is Koushik Kumar Ganeeb, working as a Principal Software Engineer at Salesforce with over 14+ years of experience in Technology & Engineering.
author_biocommittee: I feel incredibly privileged to contribute my expertise and insights as a member of various prestigious Reviewing and Judging Committees. These committees provide me with the opportunity to evaluate and assess a wide range of projects, initiatives, or submissions, ultimately playing a crucial role in recognizing excellence and promoting standards of quality within their respective fields.
author_email: "kganeeb2@gmail.com"
author_location: United States of America
author_website_url: "https://master--melodious-hamster-a1de67.netlify.app"
typewrite-text: Reach out for mentorship on Technology, Data Engineering, Integrations, Distributed Systems and to understand & leverage AI for any domain 
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Salesforce
              company_logo: salesforce.png
              company_url: https://salesforce.com
              designation: Principal Software Engineer, Data Cloud
              description: Working on building Data Connectors, Extraction Pipelines and transforming Data Cloud with AI Experiences.
              experience: 2017 - 2024*
              visibility: true
            - company_name: UnitedHealth Group Inc
              company_logo: uhg.png
              company_url: https://www.gainsight.com/
              designation: Senior Software Engineer
              description: Worked on developing a robust UHOne Dev Infrastructure setup, Clinical Healthcare Applications and Robot for automating the claims adjudication process.
              experience: 2012 - 2016
              visibility: true
            - company_name: Infosys Technologies Ltd
              company_logo: infosys.png
              company_url: https://www.infosys.com/
              designation: Systems Engineer
              description: Developed new features, critical vulnerability fixes and query optimization for the Microsoft Channel Incentives Program and improved adaptation rate.
              experience: 2010 - 2012
              visibility: true    

author_project_details:
              - project_title: IEEE Member
                project_info: IEEE membership offers access to technical innovation, cutting-edge information and access to data intelligence world wide
                project_description: IEEE is an integrated multi-functional platform and global network of technology-focused professionals, leveraging IEEE's extensive knowledge base and community of thought-leaders
                visibility: true  
              - project_title: Hackathon Raptor Fellow
                project_info: A Global Community of Technology and AI Experts committed to making a real-world impact through technology.
                project_description: Hackathon Raptor is a Community of Experts specialized on impactful challenges, top-tier Software Development, efficient Scientific Methods across the Globe, while still contributing to the betterment of the Society.
                visibility: true 
              - project_title: Proud Judge of Several International Hackathons on Technology, Innovation and AI Adaptation
                project_info: Judged several hackathons, which aims to bring together the brightest minds in technology to tackle real-world challenges and develop innovative solutions. 
                project_description: Judged Hackathons like HackSharks 2.0, HackSharks 3.0, Learn It Global, HackSwift 2024, Innovate Hacks etc
                project_url: https://hackswift.devpost.com/
                visibility: true  
              - project_title: Reviewed Articles Published in IEEE World Conference on Applied Intelligence and Computing 2024
                project_info: Reviewed Technology Advancement Articles in AIC2024
                project_description: The IEEE World Conference on Applied Intelligence and Computing is a premier international forum for researchers, practitioners, and educators to present and discuss the latest advancements in the field of applied intelligence and computing.
                project_url: https://scrs.in/conference/aic2024
                visibility: true
              - project_title: Reviewed Articles Published in International Conference on Computer, Information and Telecommunication Systems (CITS) 2024
                project_info: Reviewed Computer and Data Integration Articles in AIC2024
                project_description: The 2024 International Conference on Computer, Information, and Telecommunication Systems (CITS) serves as a platform for researchers and professionals to exchange ideas and discuss emerging trends in computer science, information technology, and telecommunications.
                project_url: https://cits.udg.edu/
                visibility: true
committee_details:
              - project_title: IEEE Technical Committee on Security and Privacy (TCSP)
                project_description: The Committee of the IEEE Computer Society that addresses operating system security, data encryption, access-control mechanisms, database protection, network security, and impact of privacy protection legislation.
                visibility: true  
              - project_title: IEEE Technical Committee on Data Engineering (TCDE)
                project_description: The Committee of the IEEE Computer Society that examines the role of data in the design, development, management, and utilization of information systems.
                visibility: true  
              - project_title: IEEE Technical Community on Cloud Computing (TCCLD)
                project_description: The Committee of the IEEE Computer Society, that promotes research, education, and industry in cloud computing.
                visibility: true  

# Education
author_education_details:
              - college_logo: cbit.png
                college_name: Chaitanya Bharathi Institute Of Technology
                college_url: https://www.cbit.ac.in/
                college_degree: Information Technology
                description: Bachelor of Engineering
                visibility: true

# social links
twitter_username: kaushikkmr
github_username: kganeeb2
adplist_username: koushik-kumar-ganeeb
facebook_username: kmr_kshk
linkedin_username: koushikganeeb

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu


# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
getform_endpoint: 3aca0b03-29ac-4f1f-b320-e737cad02512
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: devlopr
#olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_committee_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
